### ISSUE TITLE
allow a way to opt-out of ':' argument parsing

### ISSUE THREAD

**Issue by cldwalker** [zeke/queriac-rails-deprecated#23]
Hey zeke,
  Thanks for rewriting queriac to support js input - you beat me to it ;). [I see](https://github.com/zeke/queriac/blob/master/app/models/command.rb#L34) that currently ':' is a special character for named arguments. Is there a way we could opt out of it per command i.e. `my_command -- arg another_arg oops:a:colon`? I'm willing to PR for this.

**Comment by zeke** [comment]
Yeah good call. What design might circumvent the issue?

Single-quotes are also busted right now.. filing an issue now: https://github.com/zeke/queriac/issues/24. Let me know if you have any bright ideas there.

Glad to have you back on the project, man! Come work at Heroku.

**Comment by cldwalker** [comment]
My design suggestion was to support a `--` which would not parse any special syntax after it. Thoughts? Say hi to JD for me

**Comment by zeke** [comment]
I will say hello to JD.

Still not sure I grok the implementation; can you give me some example queries and resultant URLs/args?

**Comment by cldwalker** [comment]
Sure. So if I were to query with `g -- blarg site:github.com` the resulting url would be `https://www.google.com/search?q=blarg+site%3Agithub.com`. Basically a `--` after a command would determine that this command should not [parse a colon](https://github.com/zeke/queriac/blob/master/app/models/command.rb#L33-L38). I thought this was a common executable convention but the only executable I can think of right now that does this is `thor`.
